name: Proxy Scraper

on:
  workflow_dispatch:  # Bisa dijalankan manual
  schedule:
    - cron: "0 */6 * * *" # Jalan tiap 6 jam

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run proxy script
        run: |
          python proxy.py

      - name: Commit & push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add proxy-*.txt
          git commit -m "Update proxy list [auto]" || echo "No changes to commit"
          git push
